### ISSUE TITLE
Signin Backoffice (Backend)

### ISSUE THREAD

**Issue by JoseLuisSandoval** [dgsoto/Idea5-inmobiliaria#6]
**Description:**

```bash
As a admin web client I want to be able make a request to the API with credentials to start a session.
```

**Acceptance Criteria**

```bash
- The objetive sent to the route must include the "email" and "password" propterties.
- Both properties are required.
- Both propterties must be a string.
- The "email" property must be correctly formatted.
- If an error is found when receiving the object, a response will be returned with the error(s) found.
- If no errors are found and a match is found in the database with both properties, a satisfactory response will be given by returning an access token.
```

**Tasks**

- [ ] Create a dedicated endpoint (path) for authentication
- [ ] Validate the structure of the login object.
- [ ] Validate data type.
- [ ] Develop the logic to authenticate the user by comparing the credentials with the information stored in the database.
- [ ] If the credentials are valid, generate a one-time access token and return it as part of the response.
- [ ] Ensure the token has an appropriate duration and is valid for use.
- [ ] Implement robust error handling for situations like incorrect credentials, incorrect format, etc.
- [ ] Return clear and appropriate error response.
- [ ] Create unit tests to ensure the correct interaction between the different components.
- [ ] Document information about the format and duration of the access token.
